/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/vitu1234/iot-operator/pkg/apis/iot.dev/v1alpha1"
	iotdevv1alpha1 "github.com/vitu1234/iot-operator/pkg/client/applyconfiguration/iot.dev/v1alpha1"
	scheme "github.com/vitu1234/iot-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OCFDevicesGetter has a method to return a OCFDeviceInterface.
// A group's client should implement this interface.
type OCFDevicesGetter interface {
	OCFDevices(namespace string) OCFDeviceInterface
}

// OCFDeviceInterface has methods to work with OCFDevice resources.
type OCFDeviceInterface interface {
	Create(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.CreateOptions) (*v1alpha1.OCFDevice, error)
	Update(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.UpdateOptions) (*v1alpha1.OCFDevice, error)
	UpdateStatus(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.UpdateOptions) (*v1alpha1.OCFDevice, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.OCFDevice, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OCFDeviceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OCFDevice, err error)
	Apply(ctx context.Context, oCFDevice *iotdevv1alpha1.OCFDeviceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OCFDevice, err error)
	ApplyStatus(ctx context.Context, oCFDevice *iotdevv1alpha1.OCFDeviceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OCFDevice, err error)
	OCFDeviceExpansion
}

// oCFDevices implements OCFDeviceInterface
type oCFDevices struct {
	client rest.Interface
	ns     string
}

// newOCFDevices returns a OCFDevices
func newOCFDevices(c *IotV1alpha1Client, namespace string) *oCFDevices {
	return &oCFDevices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the oCFDevice, and returns the corresponding oCFDevice object, and an error if there is any.
func (c *oCFDevices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OCFDevice, err error) {
	result = &v1alpha1.OCFDevice{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OCFDevices that match those selectors.
func (c *oCFDevices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OCFDeviceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OCFDeviceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ocfdevices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested oCFDevices.
func (c *oCFDevices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ocfdevices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a oCFDevice and creates it.  Returns the server's representation of the oCFDevice, and an error, if there is any.
func (c *oCFDevices) Create(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.CreateOptions) (result *v1alpha1.OCFDevice, err error) {
	result = &v1alpha1.OCFDevice{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ocfdevices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oCFDevice).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a oCFDevice and updates it. Returns the server's representation of the oCFDevice, and an error, if there is any.
func (c *oCFDevices) Update(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.UpdateOptions) (result *v1alpha1.OCFDevice, err error) {
	result = &v1alpha1.OCFDevice{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(oCFDevice.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oCFDevice).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *oCFDevices) UpdateStatus(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.UpdateOptions) (result *v1alpha1.OCFDevice, err error) {
	result = &v1alpha1.OCFDevice{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(oCFDevice.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(oCFDevice).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the oCFDevice and deletes it. Returns an error if one occurs.
func (c *oCFDevices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *oCFDevices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ocfdevices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched oCFDevice.
func (c *oCFDevices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OCFDevice, err error) {
	result = &v1alpha1.OCFDevice{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied oCFDevice.
func (c *oCFDevices) Apply(ctx context.Context, oCFDevice *iotdevv1alpha1.OCFDeviceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OCFDevice, err error) {
	if oCFDevice == nil {
		return nil, fmt.Errorf("oCFDevice provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(oCFDevice)
	if err != nil {
		return nil, err
	}
	name := oCFDevice.Name
	if name == nil {
		return nil, fmt.Errorf("oCFDevice.Name must be provided to Apply")
	}
	result = &v1alpha1.OCFDevice{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *oCFDevices) ApplyStatus(ctx context.Context, oCFDevice *iotdevv1alpha1.OCFDeviceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OCFDevice, err error) {
	if oCFDevice == nil {
		return nil, fmt.Errorf("oCFDevice provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(oCFDevice)
	if err != nil {
		return nil, err
	}

	name := oCFDevice.Name
	if name == nil {
		return nil, fmt.Errorf("oCFDevice.Name must be provided to Apply")
	}

	result = &v1alpha1.OCFDevice{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("ocfdevices").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
