/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/vitu1234/iot-operator/pkg/apis/iot.dev/v1alpha1"
	iotdevv1alpha1 "github.com/vitu1234/iot-operator/pkg/client/applyconfiguration/iot.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOCFDevices implements OCFDeviceInterface
type FakeOCFDevices struct {
	Fake *FakeIotV1alpha1
	ns   string
}

var ocfdevicesResource = v1alpha1.SchemeGroupVersion.WithResource("ocfdevices")

var ocfdevicesKind = v1alpha1.SchemeGroupVersion.WithKind("OCFDevice")

// Get takes name of the oCFDevice, and returns the corresponding oCFDevice object, and an error if there is any.
func (c *FakeOCFDevices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OCFDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ocfdevicesResource, c.ns, name), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}

// List takes label and field selectors, and returns the list of OCFDevices that match those selectors.
func (c *FakeOCFDevices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OCFDeviceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ocfdevicesResource, ocfdevicesKind, c.ns, opts), &v1alpha1.OCFDeviceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OCFDeviceList{ListMeta: obj.(*v1alpha1.OCFDeviceList).ListMeta}
	for _, item := range obj.(*v1alpha1.OCFDeviceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oCFDevices.
func (c *FakeOCFDevices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ocfdevicesResource, c.ns, opts))

}

// Create takes the representation of a oCFDevice and creates it.  Returns the server's representation of the oCFDevice, and an error, if there is any.
func (c *FakeOCFDevices) Create(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.CreateOptions) (result *v1alpha1.OCFDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ocfdevicesResource, c.ns, oCFDevice), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}

// Update takes the representation of a oCFDevice and updates it. Returns the server's representation of the oCFDevice, and an error, if there is any.
func (c *FakeOCFDevices) Update(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.UpdateOptions) (result *v1alpha1.OCFDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ocfdevicesResource, c.ns, oCFDevice), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOCFDevices) UpdateStatus(ctx context.Context, oCFDevice *v1alpha1.OCFDevice, opts v1.UpdateOptions) (*v1alpha1.OCFDevice, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ocfdevicesResource, "status", c.ns, oCFDevice), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}

// Delete takes name of the oCFDevice and deletes it. Returns an error if one occurs.
func (c *FakeOCFDevices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ocfdevicesResource, c.ns, name, opts), &v1alpha1.OCFDevice{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOCFDevices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ocfdevicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OCFDeviceList{})
	return err
}

// Patch applies the patch and returns the patched oCFDevice.
func (c *FakeOCFDevices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OCFDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocfdevicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied oCFDevice.
func (c *FakeOCFDevices) Apply(ctx context.Context, oCFDevice *iotdevv1alpha1.OCFDeviceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OCFDevice, err error) {
	if oCFDevice == nil {
		return nil, fmt.Errorf("oCFDevice provided to Apply must not be nil")
	}
	data, err := json.Marshal(oCFDevice)
	if err != nil {
		return nil, err
	}
	name := oCFDevice.Name
	if name == nil {
		return nil, fmt.Errorf("oCFDevice.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocfdevicesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeOCFDevices) ApplyStatus(ctx context.Context, oCFDevice *iotdevv1alpha1.OCFDeviceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OCFDevice, err error) {
	if oCFDevice == nil {
		return nil, fmt.Errorf("oCFDevice provided to Apply must not be nil")
	}
	data, err := json.Marshal(oCFDevice)
	if err != nil {
		return nil, err
	}
	name := oCFDevice.Name
	if name == nil {
		return nil, fmt.Errorf("oCFDevice.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocfdevicesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.OCFDevice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCFDevice), err
}
